# Generated by Django 3.1 on 2020-10-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('m_id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('m_pw', models.CharField(max_length=12)),
                ('m_name', models.CharField(max_length=24)),
                ('m_sdrate', models.IntegerField()),
                ('m_srate', models.IntegerField()),
                ('m_frate', models.IntegerField()),
            ],
        ),
    ]
