# Generated by Django 3.1 on 2020-10-04 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('a_id', models.IntegerField(primary_key=True, serialize=False)),
                ('a_saving', models.IntegerField()),
                ('a_deposit', models.IntegerField()),
                ('a_stock', models.IntegerField()),
                ('a_fund', models.IntegerField()),
                ('m_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signup.member')),
            ],
        ),
    ]
