# Generated by Django 3.1 on 2020-11-01 05:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='a_datetime',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
