# Generated by Django 3.1 on 2020-12-01 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mypage', '0002_asset_a_datetime'),
    ]

    operations = [
        migrations.CreateModel(
            name='LovedTable',
            fields=[
                ('l_idx', models.AutoField(primary_key=True, serialize=False)),
                ('l_love', models.CharField(max_length=12)),
                ('l_loved', models.CharField(max_length=12)),
            ],
        ),
    ]
